spring:
  application:
    name: task_management_hw_t1

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    sender: bondjigaralex@yandex.ru
    recipient: chuvakchel@mail.ru
    host: smtp.yandex.ru
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

kafka:
  bootstrap:
    server: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
  consumer:
    group-id: alexgr
  session:
    timeout:
      ms: 15000
  max:
    partition:
      fetch:
        bytes: 30000
    poll:
      records: 1
      interval:
        ms: 20000
  topic:
    task_status_exchanged: task_status_exchanged
